// swift-tools-version: 5.10
import PackageDescription

let package = Package(
    name: "utitool",
    platforms: [
        .macOS(.v12) // Targets macOS 12 or later
    ],
    dependencies: [
        .package(url: "https://github.com/smittytone/clicore", branch: "develop"),
    ],
    targets: [
        .executableTarget(
            name: "utitool",
            dependencies: [
                .product(name: "Clicore", package: "clicore")
            ],
            path: "utitool",
            exclude: [
                // `Info.plist` is not a Swift source file, so its must be excluded
                // from macOS or Linux builds generated by calling the Swift compiler
                "Info.plist",
                "swift.plist"
            ],
            linkerSettings: [
                // Embed `swift.plist` into the __TEXT,__info_plist Mach-O section so the binary
                // can be signed and notarized. `.unsafeFlags` is fine here because `dlist` is
                // a top-level executable, not a library dependency.
                // macOS only: Linux has no Mach-O format and no notarization requirement.
                .unsafeFlags(
                    ["-Xlinker", "-sectcreate",
                     "-Xlinker", "__TEXT",
                     "-Xlinker", "__info_plist",
                     "-Xlinker", "utitool/swift.plist"],
                    .when(platforms: [.macOS])
                )
            ]
        )
    ]
)
