#!/bin/sh

# sync-version.sh
#
# Reads the MARKETING_VERSION and CURRENT_PROJECT_VERSION build settings from
# the dlist Xcode project and writes them into dlist/swift_version.swift, so
# that `swift build`/`swift test` report the same version and build numbers
# as the Xcode-built (and notarized) binary.
#
# The Xcode project is the source of truth: run this script after bumping
# MARKETING_VERSION/CURRENT_PROJECT_VERSION in Xcode, and before committing
# or running `swift build` directly.
#
# Usage:
#   ./sync-version.sh [configuration]
#
# `configuration` defaults to "Release" if not supplied.
#
# Copyright © 2026 Tony Smith. All rights reserved.
# Source code available under the MIT licence.

set -eu

# This script depends on xcodebuild and /usr/libexec/PlistBuddy, which are
# macOS-only tools. Abort immediately on any other platform.
if [ "$(uname)" != "Darwin" ]; then
    printf '⛔️ sync-version.sh requires macOS\n' >&2
    exit 1
fi

SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
XCODEPROJ="${SCRIPT_DIR}/utitool.xcodeproj"
TARGET_FILE="${SCRIPT_DIR}/utitool/swift_version.swift"
TARGET_PLIST="${SCRIPT_DIR}/utitool/swift.plist"
CONFIGURATION="${CONFIGURATION:-${1:-Release}}"
IN_XCODE=""

if [ -n "${MARKETING_VERSION:-}" ] && [ -n "${CURRENT_PROJECT_VERSION:-}" ]; then
    # Already running inside an Xcode build phase for a specific target/
    # configuration: Xcode has resolved these settings for us, so there's no
    # need (and, under User Script Sandboxing, no ability) to shell out to
    # xcodebuild again.
    VERSION="${MARKETING_VERSION}"
    BUILD="${CURRENT_PROJECT_VERSION}"
    IN_XCODE=1
else
    # Script run standalone
    if [ ! -d "${XCODEPROJ}" ]; then
        printf '⛔️ Cannot find %s\n' "${XCODEPROJ}" >&2
        exit 1
    fi

    if ! command -v xcodebuild >/dev/null 2>&1; then
        printf '⛔️ xcodebuild not found -- install Xcode/Command Line Tools\n' >&2
        exit 1
    fi

    BUILD_SETTINGS=$(xcodebuild -project "${XCODEPROJ}" -target dlist -configuration "${CONFIGURATION}" -showBuildSettings 2>/dev/null)

    VERSION=$(printf '%s\n' "${BUILD_SETTINGS}" | awk -F' = ' '/ MARKETING_VERSION /{print $2; exit}')
    BUILD=$(printf '%s\n' "${BUILD_SETTINGS}" | awk -F' = ' '/ CURRENT_PROJECT_VERSION /{print $2; exit}')

    if [ -z "${VERSION}" ] || [ -z "${BUILD}" ]; then
        printf '⛔️ could not read MARKETING_VERSION/CURRENT_PROJECT_VERSION from Xcode (configuration: %s)\n' "${CONFIGURATION}" >&2
        exit 1
    fi
fi

# CURRENT_PROJECT_VERSION must be a plain integer -- it's emitted as a Swift Int literal below.
case "${BUILD}" in
    ''|*[!0-9]*)
        if [ "${IN_XCODE}" = "1" ]; then
            echo "sync-version:74:error:CURRENT_PROJECT_VERSION is not a plain integer: ${BUILD}"
        else
            printf '⛔️ CURRENT_PROJECT_VERSION is not a plain integer: %s\n' "${BUILD}" >&2
        fi
        exit 1
        ;;
esac

# Escape any double quotes in the version string, just in case.
ESCAPED_VERSION=$(printf '%s' "${VERSION}" | sed 's/"/\\"/g')

cat > "${TARGET_FILE}" <<EOF
/*
    utitool
    swift_version.swift

    Copyright © 2026 Tony Smith. All rights reserved.

    MIT License
    Permission is hereby granted, free of charge, to any person obtaining a copy
    of this software and associated documentation files (the "Software"), to deal
    in the Software without restriction, including without limitation the rights
    to use, copy, modify, merge, publish, distribute, sub-license, and/or sell
    copies of the Software, and to permit persons to whom the Software is
    furnished to do so, subject to the following conditions:

    The above copyright notice and this permission notice shall be included in all
    copies or substantial portions of the Software.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
    OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
    SOFTWARE.

    NOTE This file is generated by sync-version.sh (or an equivalent Xcode Run
         Script build phase) from the version/build values set in
         dlist.xcodeproj -- do not edit it by hand. The Xcode project is the
         source of truth for the app's version and build numbers.
*/

let SWIFT_BUILD_PROCESS_VERSION = "${ESCAPED_VERSION}"
let SWIFT_BUILD_PROCESS_BUILD = ${BUILD}
EOF

printf 'Version written to %s: version %s, build %s\n' "${TARGET_FILE}" "${VERSION}" "${BUILD})"

if [ -f "${TARGET_PLIST}" ]; then
    /usr/libexec/plistbuddy -c "set CFBundleShortVersionString ${ESCAPED_VERSION}" "${TARGET_PLIST}"
    /usr/libexec/plistbuddy -c "set CFBundleVersion ${BUILD}" "${TARGET_PLIST}"
    /usr/libexec/plistbuddy -c "set CFBundleGetInfoString utitool\ ${ESCAPED_VERSION}\ copyright\ ©\ 2026,\ Tony\ Smith.\ All\ rights\ reserved" "${TARGET_PLIST}"
    
    if [ "${IN_XCODE}" = "1" ]; then
        echo "sync-version:122:error:Version written to ${TARGET_PLIST}: version ${VERSION}, build ${BUILD})"
    else
        printf 'Version written to %s: version %s, build %s\n' "${TARGET_PLIST}" "${VERSION}" "${BUILD})"
    fi
else
    if [ "${IN_XCODE}" = "1" ]; then
        echo "sync-version:122:error:Pre-formed swift.plist file missing from the source directory"
    else
        printf '⛔️ Pre-formed swift.plist file missing from the source directory'
    fi
fi

